import { isAndroid } from "..";

const TAB_ICON_SIZE = isAndroid ? 30 : 29;
const MAX_VIDEO_RECORDING_LENGTH = 5;
const MAX_VIDEO_CARD_ICON_SIZE = 26;

export { TAB_ICON_SIZE, MAX_VIDEO_RECORDING_LENGTH, MAX_VIDEO_CARD_ICON_SIZE };
